services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - checks-data:/var/lib/postgresql/data

volumes:
  checks-data:
    name: checks-data
